<?php
declare(strict_types=1);

// Ovationincentives SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

OvationincentivesUtility::setRegistrar(function (OvationincentivesUtility $u): void {
    $u->clean = [OvationincentivesClean::class, 'call'];
    $u->done = [OvationincentivesDone::class, 'call'];
    $u->make_error = [OvationincentivesMakeError::class, 'call'];
    $u->feature_add = [OvationincentivesFeatureAdd::class, 'call'];
    $u->feature_hook = [OvationincentivesFeatureHook::class, 'call'];
    $u->feature_init = [OvationincentivesFeatureInit::class, 'call'];
    $u->fetcher = [OvationincentivesFetcher::class, 'call'];
    $u->make_fetch_def = [OvationincentivesMakeFetchDef::class, 'call'];
    $u->make_context = [OvationincentivesMakeContext::class, 'call'];
    $u->make_options = [OvationincentivesMakeOptions::class, 'call'];
    $u->make_request = [OvationincentivesMakeRequest::class, 'call'];
    $u->make_response = [OvationincentivesMakeResponse::class, 'call'];
    $u->make_result = [OvationincentivesMakeResult::class, 'call'];
    $u->make_point = [OvationincentivesMakePoint::class, 'call'];
    $u->make_spec = [OvationincentivesMakeSpec::class, 'call'];
    $u->make_url = [OvationincentivesMakeUrl::class, 'call'];
    $u->param = [OvationincentivesParam::class, 'call'];
    $u->prepare_auth = [OvationincentivesPrepareAuth::class, 'call'];
    $u->prepare_body = [OvationincentivesPrepareBody::class, 'call'];
    $u->prepare_headers = [OvationincentivesPrepareHeaders::class, 'call'];
    $u->prepare_method = [OvationincentivesPrepareMethod::class, 'call'];
    $u->prepare_params = [OvationincentivesPrepareParams::class, 'call'];
    $u->prepare_path = [OvationincentivesPreparePath::class, 'call'];
    $u->prepare_query = [OvationincentivesPrepareQuery::class, 'call'];
    $u->graphql_body = [OvationincentivesGraphql::class, 'body'];
    $u->graphql_errors = [OvationincentivesGraphql::class, 'errors'];
    $u->result_basic = [OvationincentivesResultBasic::class, 'call'];
    $u->result_body = [OvationincentivesResultBody::class, 'call'];
    $u->result_headers = [OvationincentivesResultHeaders::class, 'call'];
    $u->transform_request = [OvationincentivesTransformRequest::class, 'call'];
    $u->transform_response = [OvationincentivesTransformResponse::class, 'call'];
});
